appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} | {h({l}):5.5} | {f}:{L} — {m}{n}"

  logs_backup:
    kind: rolling_file
    path: logs/psdata.log
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} | {h({l}):5.5} | {f}:{L} — {m}{n}"
    policy:
      trigger:
        kind: size
        limit: 30 mb
      roller:
        kind: delete
        count: 5
        base: 1
        
root:
  level: debug
  appenders:
    - stdout
    - logs_backup
      