appenders:
  stdout:
    kind: console

  logs_backug:
    kind: rolling_file
    path: logs/psdata.log
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} | {({l}):5.5} | {f}:{L} — {m}{n}"
    policy:
      trigger:
        kind: size
        limit: 30 mb
      roller:
        kind: fixed_window
        pattern: logs/step/step_{}.gz
        count: 5
        base: 1
        
root:
  level: debug
  appenders:
    - stdout

loggers:
  default:
    level: debug
    appenders:
      - logs_backug
      