pub const DATABASE_URL_KEY: &str = "DATABASE_URL";
pub const DATABASE_PROTOCOL_KEY: &str = "DATABASE_PROTOCOL";
pub const DATABASE_PORT_KEY: &str = "DATABASE_PORT";
pub const DATABASE_USER_KEY: &str = "POSTGRES_USER";
pub const DATABASE_PASSWORD_KEY: &str = "POSTGRES_PASSWORD";
pub const DATABASE_NAME_KEY: &str = "POSTGRES_DB";
pub const DATABASE_HOST_KEY: &str = "POSTGRES_HOST";

pub const LOG_CONFIG_PATH_KEY: &str = "LOG_CONFIG_PATH";
